### ISSUE TITLE
setData for a specific key

### ISSUE THREAD

**Issue by atoko** [ricardoalcocer/browser_localstorage_db#2]
Hello,

Currently setData forces you to save the entire document database in order to change any data. 

I'm concerned that the api makes it easy to lose data by accidentally saving the wrong information (i.e: I only wanted to update a single row, but ended up overwriting the whole database and now it only contains that single row). Is this something that can be handled by using an abstraction over these calls?

**Comment by ricardoalcocer** [comment]
PRs are accepted
